const ReportType = {
  ANC_JORONG_MONTHLY: "ANC_JORONG_MONTHLY",
  ANC_JORONG_YEARLY: "ANC_JORONG_YEARLY",
  ANC_PUSKESMAS_MONTHLY: "ANC_PUSKESMAS_MONTHLY",
  ANC_PUSKESMAS_YEARLY: "ANC_PUSKESMAS_YEARLY",
};

export default ReportType;
