version: 2.1
jobs:
  test-build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.19.0
        environment:
          PGUSER: postgres
          PGDATABASE: mch_api_test
          PGPASSWORD: password
          ACCESS_TOKEN_KEY: $ACCESS_TOKEN
          REFRESH_TOKEN_KEY: $REFRESH_TOKEN
      - image: circleci/postgres:12.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: mch_api_test
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run migrations
          command: npm run migrate up
      - run:
          name: Build
          command: npm run build

  deploy:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.19.0
        environment:
          PGUSER: postgres
          PGDATABASE: mch_api_test
          PGPASSWORD: password
          ACCESS_TOKEN_KEY: $ACCESS_TOKEN
          REFRESH_TOKEN_KEY: $REFRESH_TOKEN
      - image: circleci/postgres:12.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: mch_api_test
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - $SSH_FINGERPRINT
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Remove node_modules and .git
          command: rm -rf node_modules .git
      - run:
          name: Get current timestamp
          command: |
            echo "export TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $BASH_ENV
      - run:
          name: Create new directory for release
          command: |
            ssh -o StrictHostKeyChecking=no $AZURE_VM_USER@$AZURE_VM_IP "mkdir ~/mch-api/releases/$TIMESTAMP && chmod 777 ~/mch-api/releases/$TIMESTAMP"
      - run:
          name: Copy build files to new directory
          command: scp -o StrictHostKeyChecking=no -r ./* $AZURE_VM_USER@$AZURE_VM_IP:~/mch-api/releases/$TIMESTAMP/
      - run:
          name: Remove old releases
          command: |
            ssh -o StrictHostKeyChecking=no $AZURE_VM_USER@$AZURE_VM_IP "cd ~/mch-api/releases && ls -t | tail -n +4 | sudo xargs rm -rf"
      - run:
          name: Copy environment file to VM
          command: |
            ssh -o StrictHostKeyChecking=no $AZURE_VM_USER@$AZURE_VM_IP "sudo cp ~/config/.env ~/mch-api/releases/$TIMESTAMP/.env"
      - run:
          name: Install Dependencies on VM
          command: |
            ssh -o StrictHostKeyChecking=no $AZURE_VM_USER@$AZURE_VM_IP "cd ~/mch-api/releases/$TIMESTAMP && sudo npm install"
      - run:
          name: Run Migration on VM
          command: |
            ssh -o StrictHostKeyChecking=no $AZURE_VM_USER@$AZURE_VM_IP "cd ~/mch-api/releases/$TIMESTAMP && sudo npm run migrate up"
      - run:
          name: Restart server using pm2
          command: |
            ssh -o StrictHostKeyChecking=no $AZURE_VM_USER@$AZURE_VM_IP "cd ~/mch-api/releases/$TIMESTAMP && pm2 stop mch-api && pm2 delete mch-api && pm2 start npm --name mch-api -- start"

workflows:
  version: 2

  build:
    jobs:
      - hold:
          type: approval
          filters:
            branches: { only: [main, /(release|hotfix|v)\/.*/] }
      - test-build:
          requires:
            - hold
          filters:
            branches: { only: [main, /(release|hotfix|v)\/.*/] }
      - deploy:
          requires:
            - test-build
          filters:
            branches: { only: [main, /(release|hotfix|v)\/.*/] }
